# Generated by Django 5.0.4 on 2024-04-17 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0002_item_image_url_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='toolShare.customuser'),
        ),
    ]
