# Generated by Django 3.2.18 on 2023-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0005_auto_20230612_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
