# Generated by Django 3.2.18 on 2023-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0006_item_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
