# Generated by Django 3.2.18 on 2023-06-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0007_auto_20230613_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
