# Generated by Django 3.2.18 on 2023-06-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0008_remove_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
