# Generated by Django 3.2.18 on 2023-06-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolShare', '0009_alter_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_for_one_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
