# Generated by Django 4.2.1 on 2023-07-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("toolShare", "0010_auto_20230628_1242"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="img",
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="toolShare.item"
                    ),
                ),
            ],
        ),
    ]
