# Generated by Django 4.2.1 on 2023-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolShare", "0011_remove_item_img_itemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="img",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ItemImage",
        ),
    ]
